name: build-vati-tools
on: [push]
jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir vati-tools && cp -r target/appassembler/* vati-tools
      - uses: actions/upload-artifact@v3
        with:
          name: vati-tools-executable
          path: vati-tools/
